### PR TITLE
project got archived - updated to use new project and workflow

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/5)

### CODE REVIEW

**Review by aledj2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/5)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @aledj2, @andyb3, and @NMNS93)

___
*[config.sh, line 8 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/5#-LdsoiMD7H7kHgOYGQSa:-LdsoiMD7H7kHgOYGQSb:b3s76zf) ([raw file](https://github.com/moka-guys/dnanexus_integrity_test/blob/03fda3df3133b01b51561433b15c82ddd6057260/config.sh#L8)):*
> ```Shell
> PROJECT=project-FY4ZY8Q0ZZYX7QpYP2Fpk640
> # Workflow ID
> WORKFLOW=project-FY4ZY8Q0ZZYX7QpYP2Fpk640:workflow-FY4ZYk80ZZYf29pzBP5KgVZf
> ```

FYI any reason why this isn't WORKFLOW=$PROJECT:workflow-blah - not super important but may help in future?
___
*[GATK3.5_DNANexus_Integrity_Test_description.txt, line 11 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/5#-LdspJmE8wtUF0ue5Z-_:-LdspJmE8wtUF0ue5Z-a:ba7tbd7) ([raw file](https://github.com/moka-guys/dnanexus_integrity_test/blob/03fda3df3133b01b51561433b15c82ddd6057260/GATK3.5_DNANexus_Integrity_Test_description.txt#L11)):*
> ```
> Types               -
> Properties          -
> Tags                -
> ```

can you add the github tag to the workflow?

**Review by andyb3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/5)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @aledj2 and @NMNS93)

___
*[config.sh, line 8 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/5#-LdsoiMD7H7kHgOYGQSa:-LdsugRe9009H8Z37Y5b:b-c2aqdf) ([raw file](https://github.com/moka-guys/dnanexus_integrity_test/blob/03fda3df3133b01b51561433b15c82ddd6057260/config.sh#L8)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

FYI any reason why this isn't WORKFLOW=$PROJECT:workflow-blah - not super important but may help in future?
</blockquote></details>

Have moved workflow to 001 (it's now in it's own repo) so the project ID is different
___
*[GATK3.5_DNANexus_Integrity_Test_description.txt, line 11 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/5#-LdspJmE8wtUF0ue5Z-_:-LdsuQWqDNbW47Lp7R5e:b-z9vppr) ([raw file](https://github.com/moka-guys/dnanexus_integrity_test/blob/03fda3df3133b01b51561433b15c82ddd6057260/GATK3.5_DNANexus_Integrity_Test_description.txt#L11)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can you add the github tag to the workflow?
</blockquote></details>

Have moved the workflow to it's own repo so it can have a github release: https://github.com/moka-guys/dnanexus_platform_integrity_test_workflow

**Review by aledj2 — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NMNS93)

**Review by aledj2 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/5#-:-LdsvYRW0wJ-EIvB7ee2:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NMNS93)

**Pull request merged**
