### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/1)

### CODE REVIEW

**Comment by aledj2** [comment]
I have created a issue to add the updated crontab to github

---

Reviewed 1 of 5 files at r1.
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[config.sh, line 1 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_integrity_test/1#-Kz-aTciZFjLQ5c47vV0:-Kz-aTciZFjLQ5c47vV1:bj3vgqm) ([raw file](https://github.com/moka-guys/dnanexus_integrity_test/blob/c7fdd9cb6f0ca706c46d62797c72257e89458928/config.sh#L1)):*
> ```Shell
> DX_ENV=/etc/profile.d/dnanexus.environment.sh
> ```

would comments break this file?

---

*[DNANexus_Integrity_Check.sh, line 30 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_integrity_test/1#-Kz-a3EakNSn2Ul06uU9:-Kz-a3EakNSn2Ul06uUA:b7237fu) ([raw file](https://github.com/moka-guys/dnanexus_integrity_test/blob/c7fdd9cb6f0ca706c46d62797c72257e89458928/DNANexus_Integrity_Check.sh#L30)):*
> ```Shell
> dx run ${PROJECT}:${WORKFLOW} -y --wait --brief --rerun-stage "*" \
> --tag ${timestamp} --dest=${PROJECT}:${timestamp} --auth-token ${API_KEY}
> # Find all analyses matching the timestamp tag. Returns matching analysis IDs (should only be one) separated by spaces.
> ```

FYI the tag --wait was used so the script won't continue until the analysis is finished

---

*[DNANexus_Integrity_Check.sh, line 54 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_integrity_test/1#-Kz-ZiYEok98EUupe0Uc:-Kz-ZiYEok98EUupe0Ud:bloxoig) ([raw file](https://github.com/moka-guys/dnanexus_integrity_test/blob/c7fdd9cb6f0ca706c46d62797c72257e89458928/DNANexus_Integrity_Check.sh#L54)):*
> ```Shell
>         truth_filenames=$(python -c "print sorted([file['describe']['name'] for file in ${truth_files_json}])")
>         # Check that the test and truth set contain exactly the same filenames  
>         if [[ "${test_filenames}" = "${truth_filenames}" ]]; then
> ```

BTW - we discussed that this tests the outputs of the workflows are the same - there is no need to test that the correct file was passed as an input as this would most likely result in the tool failing, eg a BAM file being passed into the input for a BED file etc

---

*[DNANexus_Integrity_Check.sh, line 69 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_integrity_test/1#-Kz-aXaJKo1RUqyRM4YB:-Kz-aXaJKo1RUqyRM4YC:bv2ivz1) ([raw file](https://github.com/moka-guys/dnanexus_integrity_test/blob/c7fdd9cb6f0ca706c46d62797c72257e89458928/DNANexus_Integrity_Check.sh#L69)):*
> ```Shell
>     # write a failure message to syslog including the number of analyses that were returned
>     logger -t DNANexus-integrity-test "FAIL - The number of analyses with tag matching ${timestamp} was not 1. (Matching files: ${all_analyses_count})"
> fi
> ```

FYI lots of good comments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_integrity_test/1#-:-Kz-aqyD8mNZJxJclXXN:bdi8j2p)*

**Comment by aledj2** [comment]
Reviewed 1 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_integrity_test/1)*

**Comment by andyb3** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[config.sh, line 1 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_integrity_test/1#-Kz-aTciZFjLQ5c47vV0:-Kz4qd01WpPBaM-zjQ6o:b-i726zx) ([raw file](https://github.com/moka-guys/dnanexus_integrity_test/blob/c7fdd9cb6f0ca706c46d62797c72257e89458928/config.sh#L1)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

would comments break this file?
</blockquote></details>

Nope! Have added some in

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_integrity_test/1)*

**Comment by aledj2** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_integrity_test/1#-:-L-7qPlIQFwxU7_OXvSS:bnfp4nl)*

**Pull request merged**
