### PR TITLE
v1.1

### PR DESCRIPTION
**Pull request by andyb3**
- Use project ID rather than name (need to update name because it doesn't follow correct naming convention)
- Use shared API key file

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/3)

### CODE REVIEW

**Review by aledj2 — COMMENTED** [review]
+@aledj2 

> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/3#-:-Lca1_dk1ixALWSb-Myk:bweg3f8)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @aledj2, @Graeme-Smith, and @NMNS93)

**Review by aledj2 — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/3)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @andyb3, @Graeme-Smith, and @NMNS93)

___
*[README.md, line 13 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/3#-Lca2NUkAXW3G4z60pEW:-Lca2NUkAXW3G4z60pEX:brhdgvo) ([raw file](https://github.com/moka-guys/dnanexus_integrity_test/blob/43045575667570bcfb035b7647631c52a5c36e64/README.md#L13)):*
> ```Markdown
> * `config.sh`
> 
> The first two can be found in this repository. The settings for the script are stored in the `config.sh` file so that they can be easily updated. The `api_key.sh` file must be created and should contain the following line:
> ```

is mentioning that the settings are in the config.sh sufficient to cover where the api key should be saved?

**Review by andyb3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/3)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @aledj2, @Graeme-Smith, and @NMNS93)

___
*[DNANexus_Integrity_Check.sh, line 13 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/3#-LcaG_7TBOD08xIs3HXN:-LcaG_7TBOD08xIs3HXO:br01vwe) ([raw file](https://github.com/moka-guys/dnanexus_integrity_test/blob/43045575667570bcfb035b7647631c52a5c36e64/DNANexus_Integrity_Check.sh#L13)):*
> ```Shell
> # Read DNAnexus API key from file.
> API_KEY=$(<../../.dnanexus_auth_token)
> # Source the public config file containing other environment variables.
> ```

Realised that when I was testing this I was testing it from within the folder it was run in, but if you run from outside (e.g. cronjob) the relative filepaths won't work! Have changed to a hardcoded file path in the config file
___
*[README.md, line 13 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/3#-Lca2NUkAXW3G4z60pEW:-LcaGn0DB3rnG5HdhAB-:bi76uuj) ([raw file](https://github.com/moka-guys/dnanexus_integrity_test/blob/43045575667570bcfb035b7647631c52a5c36e64/README.md#L13)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

is mentioning that the settings are in the config.sh sufficient to cover where the api key should be saved?
</blockquote></details>

Removed this section as no longer relevant

**Review by aledj2 — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/3)* status: all files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith and @NMNS93)

**Review by aledj2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/3)* status: all files reviewed, 1 unresolved discussion (waiting on @andyb3, @Graeme-Smith, and @NMNS93)

**Review by aledj2 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_integrity_test/3#-:-LcaHq1S9VC0Pl6hoOYf:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @andyb3, @Graeme-Smith, and @NMNS93)

**Pull request merged**
